title : Jeremy Ong
tagline: You know how it is how we know what we do
author :
  name : Jeremy Ong
  email : jeremy@playmesh.com
  github : jeremyong

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
